// authentication
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const RETRIEVE_TEMPORARY_ACCESS_TOKEN = 'RETRIEVE_TEMPORARY_ACCESS_TOKEN';
export const RETRIEVE_ACCESS_TOKEN = 'RETRIEVE_ACCESS_TOKEN';

// athlete
export const GET_ATHLETE_DETAILS = 'GET_ATHLETE_DETAILS';
export const GET_ATHLETE_STATS = 'GET_ATHLETE_STATS';
export const GET_ATHLETE_ACTIVITIES = 'GET_ATHLETE_ACTIVITIES';
export const GET_ATHLETE_GEAR = 'GET_ATHLETE_GEAR';
export const GET_ATHLETE_CLUBS = 'GET_ATHLETE_CLUBS';

export const RETRIEVE_ATHLETE_DETAILS = 'RETRIEVE_ATHLETE_DETAILS';
export const RETRIEVE_ATHLETE_STATS = 'RETRIEVE_ATHLETE_STATS';
export const RETRIEVE_ATHLETE_ACTIVITIES = 'RETRIEVE_ATHLETE_ACTIVITIES';
export const RETRIEVE_ATHLETE_GEAR = 'RETRIEVE_ATHLETE_GEAR';
export const RETRIEVE_ATHLETE_CLUBS = 'RETRIEVE_ATHLETE_CLUBS';
