export const references = {
  BIGGEST_DISTANCE: 164600, // Diagonale des fous race distance
  BIGGEST_ELEVATION_GAIN: 9576000, // Diagonale des fous race elevation gain
  RECENT_RUN_COUNT: 31,
  RECENT_RUN_DISTANCE: 220000, // GRP Ultra Tour race distance
  RECENT_ACHIEVEMENT_COUNT: 12,
  RECENT_RUN_ELEVATION_GAIN: 6100, // CCC race elevation gain
  RECENT_RUN_SPEED: 4,
  RECENT_RUN_TIME: 144000, // 40 hours
  YEAR_RUN_COUNT: 365,
  YEAR_RUN_DISTANCE: 1212000, // CCC race distance * 12
  YEAR_ACHIEVEMENT_COUNT: 49,
  YEAR_RUN_ELEVATION_GAIN: 73200, // CCC race elevation gain * 12
  TOTAL_RUN_COUNT: 9999,
  TOTAL_RUN_DISTANCE: 12120000, // CCC race distance * 120
  TOTAL_ACHIEVEMENT_COUNT: 9999,
  TOTAL_RUN_ELEVATION_GAIN: 884800 // Everest elevation gain * 100
};

export const referencesWeightings = {
  BIGGEST_DISTANCE: 0.5,
  BIGGEST_ELEVATION_GAIN: 0.5,
  RECENT_RUN_COUNT: 0.2,
  RECENT_RUN_DISTANCE: 0.2,
  RECENT_RUN_SPEED: 0.2,
  RECENT_RUN_TIME: 0.2,
  RECENT_ACHIEVEMENT_COUNT: 0.1,
  RECENT_RUN_ELEVATION_GAIN: 0.2,
  YEAR_RUN_COUNT: 0.2,
  YEAR_RUN_DISTANCE: 0.3,
  YEAR_ACHIEVEMENT_COUNT: 0.1,
  YEAR_RUN_ELEVATION_GAIN: 0.4,
  TOTAL_RUN_COUNT: 0.2,
  TOTAL_RUN_DISTANCE: 0.4,
  TOTAL_RUN_ELEVATION_GAIN: 0.4,
  TOTAL_EFFORTS: 0.2,
  RECENT_EFFORTS: 0.3,
  YEAR_EFFORTS: 0.5
};
