export const references = {
  BIGGEST_DISTANCE: 164600, // Diagonale des fous race distance
  BIGGEST_ELEVATION_GAIN: 9576000, // Diagonale des fous race elevation gain
  RECENT_RUN_COUNT: 31,
  RECENT_RUN_DISTANCE: 101000, // CCC race distance
  RECENT_ACHIEVEMENT_COUNT: 12,
  RECENT_RUN_ELEVATION_GAIN: 6100, // CCC race elevation gain
  YEAR_RUN_COUNT: 365,
  YEAR_RUN_DISTANCE: 1212000, // CCC race distance * 12
  YEAR_ACHIEVEMENT_COUNT: 49,
  YEAR_RUN_ELEVATION_GAIN: 73200 // CCC race elevation gain * 12
};

export const referencesWeighting = {
  BIGGEST_DISTANCE: 0.5,
  BIGGEST_ELEVATION_GAIN: 0.5,
  RECENT_RUN_COUNT: 0.2,
  RECENT_RUN_DISTANCE: 0.3,
  RECENT_ACHIEVEMENT_COUNT: 0.1,
  RECENT_RUN_ELEVATION_GAIN: 0.4,
  YEAR_RUN_COUNT: 0.2,
  YEAR_RUN_DISTANCE: 0.3,
  YEAR_ACHIEVEMENT_COUNT: 0.1,
  YEAR_RUN_ELEVATION_GAIN: 0.4,
  BIGGEST_EFFORT: 0.2,
  RECENT_EFFORTS: 0.3,
  YEAR_EFFORTS: 0.5
};
